# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksbuilder < Formula
  desc ""
  homepage "https://github.com/kubesphere/ksbuilder"
  version "0.0.1-alpha1"

  on_macos do
    url "https://github.com/kubesphere/ksbuilder/releases/download/v0.0.1-alpha1/ksbuilder_0.0.1-alpha1_darwin_all.tar.gz"
    sha256 "2de6dabc7e6a1e378498d050f2bec4131ecec57df582e67f1f85a20b6555b033"

    def install
      bin.install "ksbuilder"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesphere/ksbuilder/releases/download/v0.0.1-alpha1/ksbuilder_0.0.1-alpha1_linux_arm64.tar.gz"
      sha256 "e20fc84803cc459aef02e751d0f52384ef86871918cd116c60a5e25237ef2716"

      def install
        bin.install "ksbuilder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubesphere/ksbuilder/releases/download/v0.0.1-alpha1/ksbuilder_0.0.1-alpha1_linux_amd64.tar.gz"
      sha256 "42c703d35d8b8385581b41ac0bd76fb812802a6f5b00d81f3ba8947f4384302d"

      def install
        bin.install "ksbuilder"
      end
    end
  end
end
