# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksc < Formula
  desc ""
  homepage "https://github.com/chenz24/ks-cli"
  version "0.0.1-alpha2"

  on_macos do
    url "https://github.com/chenz24/ks-cli/releases/download/v0.0.1-alpha2/ks-cli_0.0.1-alpha2_darwin_all.tar.gz"
    sha256 "521b999b4ad4ceb0a0bfeadf49fe0221ed41e41ff03168d79d96e2f2a28f1883"

    def install
      bin.install "ks-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chenz24/ks-cli/releases/download/v0.0.1-alpha2/ks-cli_0.0.1-alpha2_linux_amd64.tar.gz"
      sha256 "d2ce922a80193b37a4b36f6cfee616cd61b50db6052419cc66c878b85df33e19"

      def install
        bin.install "ksc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenz24/ks-cli/releases/download/v0.0.1-alpha2/ks-cli_0.0.1-alpha2_linux_arm64.tar.gz"
      sha256 "2ba504f16488f933e99b12479923c0200d3be0c3d9ed197de633f9760616fa38"

      def install
        bin.install "ksc"
      end
    end
  end
end
