# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksnext < Formula
  desc ""
  homepage "https://github.com/chenz24/ksnext"
  version "0.0.1-alpha5"

  on_macos do
    url "https://github.com/chenz24/ksnext/releases/download/v0.0.1-alpha5/ksnext_0.0.1-alpha5_darwin_all.tar.gz"
    sha256 "d729fba9701c201bfb2d2b6a92a2a4a1e19217b22862435043ebffd8f4bfbf53"

    def install
      bin.install "ksnext"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chenz24/ksnext/releases/download/v0.0.1-alpha5/ksnext_0.0.1-alpha5_linux_arm64.tar.gz"
      sha256 "0e750a0ba9032d89d0e4670dfc99768926e9576e93de5dbe112dba79e08408d2"

      def install
        bin.install "ksnext"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chenz24/ksnext/releases/download/v0.0.1-alpha5/ksnext_0.0.1-alpha5_linux_amd64.tar.gz"
      sha256 "ca0bb999742437047cbefbfbbf16ff37b05b5f3ccdf48c9cf88e506ee87316b1"

      def install
        bin.install "ksnext"
      end
    end
  end
end
